# Agenda

1. 2D NumPy
2. Pandas
    - Series (1D)
    - Data frame (2D)
3. Reading from CSV

In [1]:
import numpy as np

In [5]:
np.random.seed(0)
a = np.random.randint(0, 100, 20)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [3]:
a.dtype

dtype('int64')

In [7]:
np.random.seed(0)
a = np.random.randint(0, 100, 20, dtype=np.int8)
a

array([44, 10, 12, 47, 42, 68, 23, 38, 22, 55, 64, 76, 33, 88, 67, 51, 78,
       26, 82, 34], dtype=int8)

In [8]:
b = np.array([10, 20, 30, 40])

In [9]:
a + b

ValueError: operands could not be broadcast together with shapes (20,) (4,) 

In [10]:
a.shape

(20,)

In [11]:
b.shape

(4,)

In [12]:
a.shape = (5, 4)

In [13]:
a

array([[44, 10, 12, 47],
       [42, 68, 23, 38],
       [22, 55, 64, 76],
       [33, 88, 67, 51],
       [78, 26, 82, 34]], dtype=int8)

In [14]:
np.random.seed(0)
a = np.random.randint(0, 100, 20, dtype=np.int8).reshape(5, 4)

In [15]:
a

array([[44, 10, 12, 47],
       [42, 68, 23, 38],
       [22, 55, 64, 76],
       [33, 88, 67, 51],
       [78, 26, 82, 34]], dtype=int8)

In [16]:
np.random.seed(0)
a = np.random.randint(0, 100, [5,4], dtype=np.int8)
a

array([[44, 10, 12, 47],
       [42, 68, 23, 38],
       [22, 55, 64, 76],
       [33, 88, 67, 51],
       [78, 26, 82, 34]], dtype=int8)

In [19]:
# how can I get to 64?

a[2][2]    # don't do this, even if it works

64

In [21]:
a[2,2]    # this is how we should retrieve from NumPy

64

In [22]:
a[0, 2]

12

In [23]:
a[2, 3]

76

In [24]:
a[(2,3)]

76

In [25]:
# what if I want both 55 and 64 from index 2?

a[2, [1,2]]      # row index 2, 

array([55, 64], dtype=int8)

In [26]:
a[2, 1:3]

array([55, 64], dtype=int8)