# Agenda

1. Threading exceptions
2. `asyncio` -- ideas + examples
3. Benchmarking
4. NumPy + `pandas`

# Benchmarking

In [10]:
def traditional_loop():
    numbers = range(10_000_000)
    
    output = []
    for one_number in numbers:
        output.append(one_number ** 2)
        
    return output

def comprehension():
    numbers = range(10_000_000)
    
    return [one_number ** 2
           for one_number in numbers]



In [11]:
import time
start_time = time.perf_counter()
traditional_loop()
end_time = time.perf_counter()

print(f'Took {end_time - start_time}')

Took 2.5332047143019736


In [12]:
import time
start_time = time.perf_counter()
comprehension()
end_time = time.perf_counter()

print(f'Took {end_time - start_time}')

Took 2.1925993440672755


In [16]:
# everything we pass to %timeit needs to be on one line!
%timeit traditional_loop()

SyntaxError: unmatched ')' (1912264951.py, line 2)

In [14]:
%timeit comprehension()

2.22 s ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
# Non-Jupyter magic command version of timeit
import timeit



In [22]:
traditional_loop = '''
numbers = range(10_000_000)

output = []
for one_number in numbers:
    output.append(one_number ** 2)
'''

comprehension = '''
numbers = range(10_000_000)

output = [one_number ** 2
       for one_number in numbers]
'''

timeit.timeit(traditional_loop, number=10)

24.426533837802708

In [23]:
timeit.timeit(comprehension, number=10)

22.13207621080801

In [24]:
help(timeit.timeit)

Help on function timeit in module timeit:

timeit(stmt='pass', setup='pass', timer=<built-in function perf_counter>, number=1000000, globals=None)
    Convenience function to create Timer object and call timeit method.



In [26]:
def traditional_loop():
    numbers = range(10_000_000)
    
    output = []
    for one_number in numbers:
        output.append(one_number ** 2)
        
    return output

def comprehension():
    numbers = range(10_000_000)
    
    return [one_number ** 2
           for one_number in numbers]

timeit.timeit('traditional_loop()', number=3, globals=globals())

7.442414263263345

In [27]:
timeit.timeit('comprehension()', number=3, globals=globals())

6.650881435722113

# NumPy and Pandas

In [28]:
import sys
x = 0
sys.getsizeof(x)

24

# NumPy

NumPy gives us one data structure: `ndarray` (n-dimensional array).  But don't call it directly -- instead, call `np.array` to create a new NumPy array.



In [29]:
import numpy as np   # everyone uses this alias

a = np.array([10,20, 30, 40, 50])

In [30]:
type(a)

numpy.ndarray

In [31]:
a

array([10, 20, 30, 40, 50])

In [32]:
a[0]

10

In [33]:
a[1]

20

In [34]:
a[0] = 50

In [35]:
a

array([50, 20, 30, 40, 50])

In [36]:
a[0] = 10

In [37]:
a

array([10, 20, 30, 40, 50])

In [38]:
mylist = [10, 20, 30, 40, 50]
mylist + mylist  # what happens when we add a list to itself?

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [39]:
a + a   # what happens when I add a + a?

array([ 20,  40,  60,  80, 100])

In [40]:
b = np.array([100, 200, 300])

In [41]:
a + b

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [42]:
a

array([10, 20, 30, 40, 50])

In [44]:
a + 3    # broadcast

array([13, 23, 33, 43, 53])

In [45]:
a - 3

array([ 7, 17, 27, 37, 47])

In [47]:
a * 3

array([ 30,  60,  90, 120, 150])

In [48]:
a / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [49]:
a // 3

array([ 3,  6, 10, 13, 16])

In [50]:
a ** 3

array([  1000,   8000,  27000,  64000, 125000])

In [51]:
a % 3

array([1, 2, 0, 1, 2])

In [ ]:
a[[2, 4]]   # fancy i